User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - control'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
> conda --version
> pyenv root
> python3.7 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /usr/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
Error 2020-07-31 07:32:44: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/tomicp/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/tomicp/.config/Code/User/settings.json')
	at _handleError (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:657:25)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async v.readText (/home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:1:571152)
	at async p.doesFileNeedToBeFixed (/home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:932463)
	at async /home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:931590
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:931536)
	at async p.updateTestSettings (/home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:931163)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2020-07-31 07:32:44: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/tomicp/PycharmProjects/Giraffe/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/tomicp/PycharmProjects/Giraffe/.vscode/settings.json')
	at _handleError (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:657:25)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async v.readText (/home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:1:571152)
	at async p.doesFileNeedToBeFixed (/home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:932463)
	at async /home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:931590
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:931536)
	at async p.updateTestSettings (/home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/out/client/extension.js:48:931163)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Starting Jedi Python language engine.
Python interpreter path: ./venv/bin/python3.8
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/PycharmProjects/Giraffe/app.py
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/PycharmProjects/Giraffe/app.py
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/PycharmProjects/Giraffe
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/completion.py
> ~/PycharmProjects/Giraffe/venv/bin/python3.8 ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/pyvsc-run-isolated.py ~/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/completion.py
> conda --version
Error 2020-07-31 07:32:46: stderr jediProxy Error (stderr) /home/tomicp/.vscode-oss/extensions/ms-python.python-2020.7.0/pythonFiles/completion.py:586: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

##########Linting Output - pylint##########

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

